// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBnY7hO4-cedo2FuC79Rrrm_8u36Nzw5g',
    appId: '1:416566307144:android:b65b915738531417ef6b7d',
    messagingSenderId: '416566307144',
    projectId: 'gigu-8ed82',
    databaseURL: 'https://gigu-8ed82-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gigu-8ed82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB__L6x7fUbxIlFMvkMO_DibZCiOK4boos',
    appId: '1:416566307144:ios:1461ab9611689238ef6b7d',
    messagingSenderId: '416566307144',
    projectId: 'gigu-8ed82',
    databaseURL: 'https://gigu-8ed82-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gigu-8ed82.appspot.com',
    iosClientId: '416566307144-cr1d12gd7po62qafl8to3ne4d2j8d835.apps.googleusercontent.com',
    iosBundleId: 'io.gigu.beer',
  );
}
